---
- name: APT | Install packages
  apt:
    name:
      - lvm2
      - scsitools
      - xfsprogs
      - jq
      - nfs-common
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: debian | checking for scsi devices
  ansible.builtin.command: sg_scan
  become: true
  register: scsi_devices
  changed_when: false

- name: debian | rescanning for new disks added
  ansible.builtin.command: /usr/bin/rescan-scsi-bus.sh
  become: true
  changed_when: false
  when: scsi_devices['stdout'] | length > 0
