---
##################################################
#                Disable Firewalld               #
##################################################
- name: Stop and mask firewalld if installed
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes
  when:
    - ansible_facts.services['firewalld.service'] is defined
